version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Baku # Set timezone
    volumes:
      - ./csv:/usr/src/app/csv # Mount csv folder
